//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_Higher_Institution
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_program_add
    {
        public int p_id { get; set; }
        public string faculty { get; set; }
        public string department { get; set; }
        public string program { get; set; }
        public string code { get; set; }
        public string Registered_by { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime dat { get; set; }
    }
}
