//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_Higher_Institution
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_grading_system
    {
        public int p_id { get; set; }
        public decimal from1 { get; set; }
        public decimal to1 { get; set; }
        public string grade { get; set; }
        public decimal gp1 { get; set; }
        public decimal gp2 { get; set; }
        public string remark { get; set; }
        public string code { get; set; }
        public string classification { get; set; }
        public string registered_by { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime last_updated { get; set; }
    }
}
