//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_Higher_Institution
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_user
    {
        public int p_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string full_name { get; set; }
        public string matric_no { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime dat { get; set; }
    }
}
