//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_Higher_Institution
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_course_register
    {
        public int p_id { get; set; }
        public string student_name { get; set; }
        public string matric_no { get; set; }
        public string course { get; set; }
        public string course_code { get; set; }
        public string code { get; set; }
        public string unit { get; set; }
        public string status { get; set; }
        public string level { get; set; }
        public string Semester { get; set; }
        public string calendar_year { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime dat { get; set; }
    }
}
