//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_Higher_Institution
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_staff
    {
        public int p_id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string full_name { get; set; }
        public string qualification { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string position { get; set; }
        public string code { get; set; }
        public string date_employed { get; set; }
        public string registered_by { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime dat { get; set; }
    }
}
