//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_Higher_Institution
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_course_add
    {
        public int p_id { get; set; }
        public string course { get; set; }
        public string course_code { get; set; }
        public string Unit { get; set; }
        public string Level { get; set; }
        public string registered_by { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime dat { get; set; }
    }
}
