//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_Higher_Institution
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_students
    {
        public int p_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string student_name { get; set; }
        public string matric_no { get; set; }
        public string date_of_birth { get; set; }
        public string place_of_birth { get; set; }
        public string sex { get; set; }
        public string nationality { get; set; }
        public string marital_status { get; set; }
        public string age { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string code { get; set; }
        public string sponsor_name { get; set; }
        public string sponsor_address { get; set; }
        public string sponsor_relationship { get; set; }
        public string sponsor_occupation { get; set; }
        public string sponsor_phone { get; set; }
        public string sponsor_email { get; set; }
        public string highest_qualification { get; set; }
        public string qualification { get; set; }
        public string year_of_admission { get; set; }
        public string faculty { get; set; }
        public string department { get; set; }
        public string program { get; set; }
        public string mode { get; set; }
        public string campus { get; set; }
        public string note { get; set; }
        public string status { get; set; }
        public string registered_by { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime dat { get; set; }
    }
}
